
[mgr]
ratio = [0, 3, 6]

[plugin]
prepend_previewers = [
  { mime = "text/csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.json", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
]

prepend_preloaders = [
  { mime = "text/csv", run = "duckdb" },
  { url = "*.tsv", run = "duckdb" },
  { url = "*.json", run = "duckdb" },
  { url = "*.parquet", run = "duckdb" },
]
